<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Settings</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="/css/svgStyles.css" rel="stylesheet">
    <link href="/css/pageStyle.css" rel="stylesheet">
</head>
<body class="bg-light">
<?php
$previousPassword = $form->get('prevPassword');
$newPassword      = $form->get('newPassword');
$repeatPassword   = $form->get('repeatPassword');
$submit           = $form->get('submit');

$form->setAttribute('class', 'needs-validation');
$form->setAttribute('novalidate', 'true');
$form->prepare();

echo $this->formHidden($form->get('id'));
?>
<main class="d-flex">
    <div class="d-flex flex-column align-items-stretch flex-shrink-0 min-vh-100">
        <div class="d-flex align-items-center flex-shrink-0 p-2 link-dark text-decoration-none" style="position: absolute;
                                                                                                       top: 0;
                                                                                                       left: 0;
                                                                                                       width: 100%;
                                                                                                       background-color: #f2f0f0;
                                                                                                       opacity: 0.7;
                                                                                                       box-shadow: 0 10px 10px rgba(0, 0, 0, .3);
                                                                                                       ">
            <img class="bi pe-none me-2" id="navPict" src="/img/settings.svg">
            <span class="fs-5 fw-bold me-3">Change password</span>
        </div>
        <div class="scrollarea" style="background-color: #f2f0f0; width: 160%; margin-left: 20%; margin-top: 25%; border-radius: 6%;">
            <?php echo $this->form()->openTag($form); ?>
            <div class="mt-0 p-3 pt-1 bg-light rounded shadow-sm">
                <div class="d-flex mt-xxl-5">
                    <label class="w-auto">Enter previous password</label>
                    <?php echo $this->formElement($previousPassword) ?>
                </div>
                <div class="d-flex mt-xxl-5 position-relative">
                    <label class="w-auto me-4">Enter new password</label>
                    <?php echo $this->formElement($newPassword) ?>
                    <div class="invalid-tooltip" id="warningMesNewPassword">
                        Password do not be less 8 letters!
                    </div>
                </div>
                <div class="d-flex mt-xxl-5 position-relative">
                    <label class="w-auto me-sm-3">Repeat new password</label>
                    <?php echo $this->formElement($repeatPassword) ?>
                    <div class="invalid-tooltip">
                        Passwords aren't equal!!!
                    </div>
                </div>
                <div class="text-center">
                    <?php echo $this->formButton($submit, 'Change password'); ?>
                </div>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</main>
<script src="/js/jquery-3.5.1.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script type="module" src="/js/validation/validationChangePassword.js"></script>
<script type="module" src="/js/validation/validation.js"></script>
</body>
</html>



