<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign in</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="/css/pageStyle.css" rel="stylesheet">
    <link href="/css/svgStyles.css" rel="stylesheet">

    <style>
        .arrow-2 {
            cursor: pointer;
            height: 120px;
            width: 80px;
            position: relative;
            margin-left: 25%;
        }
        .arrow-2-top,
        .arrow-2-bottom {
            background: #337AB7;
            height: 3px;
            position: absolute;
            top: 60px;
            width: 40px;
        }
        .arrow-text {
            color: #337AB7;
            font-weight: bold;
            position: absolute;
            top: 48px;
            margin-left: 55px;
            font-size: 1.3em;
        }
        .arrow-2-top {
            top: 66px;
        }
        .arrow-2-top {
            transform: rotate(-160deg);
            transform-origin: top right;
        }
        .arrow-2-bottom {
            transform: rotate(160deg);
            transform-origin: bottom right;
        }
        .arrow-2-top::after,
        .arrow-2-bottom::after {
            background: #000;
            content: '';
            height: 100%;
            position: absolute;
            top: 0;
            transition: all 0.15s;
        }
        .arrow-2-top::after {
            left: 100%;
            right: 0;
            transition-delay: 0s;
        }
        .arrow-2-bottom::after {
            left: 0;
            right: 100%;
            transition-delay: 0.15s;
        }
        .arrow-2:hover .arrow-2-top::after {
            left: 0;
            transition-delay: 0.15s;
        }
        .arrow-2:hover .arrow-2-bottom::after {
            right: 0;
            transition-delay: 0s;
        }
    </style>

    <script>
       function showPage() {
           document.getElementById("forgotPasswordPage").hidden = true;
           document.getElementById("registerPage").hidden = true;
           document.getElementById("signInPage").hidden = false;
       }
      </script>

</head>
<body>
<?php
$emailSignIn = $form->get('emailSignIn');
$emailSignIn->setAttribute('name', 'email[]');

$emailRegistration = $form->get('emailRegister');
$emailRegistration->setAttribute('name', 'email[]');

$emailForgotPassword = $form->get('emailForgotPassword');
$emailForgotPassword->setAttribute('name', 'email[]');

$passwordSignIn   = $form->get('passwordSignIn');
$passwordRegister = $form->get('passwordRegister');
$repeatPassword   = $form->get('repeatPassword');

$submit         = $form->get('submit');
$submitRegister = $form->get('submitRegister');


$form->setAttribute('class', 'needs-validation');
$form->setAttribute('novalidate', 'true');
$form->prepare();

echo $this->formHidden($form->get('id'));
?>
<div class="text-center">
    <main class="w-100 position-absolute text-center startPageMargin" id="signInPage">
        <?php echo $this->form()->openTag($form); ?>
        <h1 class="mb-5">Sign in</h1>
        <div class="position-relative justify-content-lg-center">
            <?php echo $this->formElement($emailSignIn); ?>
            <div class="invalid-tooltip" name="warningMesEmail">
                Incorrect email!
            </div>
        </div>
        <div class="position-relative mt-4 justify-content-lg-center">
            <?php echo $this->formElement($passwordSignIn); ?>
            <div class="invalid-tooltip" id="warningMesPassword">
                Incorrect Password!
            </div>
        </div>
        <div class="mt-1 mb-3">
            <a href="#" id="forgotPasswordButton" class="m-3"> Forgot password? </a>
        </div>
        <?php echo $this->formButton($form->get('submit'), 'Sign in'); ?>
        <div class="checkbox mb-3 mt-2">
            <input class="form-check-input" type="checkbox" value="remember-me" id="invalidCheck" required>
            <label class="form-check-label" for="invalidCheck">
                Remember me
            </label>
        </div>
        <div class="m-3">
            <a href="#" id="registerButton" class="m-3">Don't have an account? Make it!</a>
        </div>
        <?php echo $this->form()->closeTag(); ?>

    </main>

    <div class="position-absolute w-100" id="forgotPasswordPage" hidden>
        <div class="arrow-2" onclick="showPage()">
            <div class="arrow-2-top"></div>
            <div class="arrow-2-bottom"></div>
            <span class="arrow-text">Back</span>
        </div>
        <?php echo $this->form()->openTag($form); ?>
        <h1 class="text-center">Password recovery</h1>
        <p>Enter your email address, so we can send you new password</p>
        <div class="position-relative mt-5 justify-content-lg-center">
            <?php echo $this->formElement($emailForgotPassword); ?>
            <div class="invalid-tooltip" id="warningMesEmail">
                Incorrect email!
            </div>
        </div>
        <?php echo $this->formButton($submit, 'Send'); ?>
        <?php echo $this->form()->closeTag(); ?>
    </div>

    <main class="w-100" style="margin: auto;" id="registerPage" hidden>
        <div class="arrow-2" onclick="showPage()">
            <div class="arrow-2-top"></div>
            <div class="arrow-2-bottom"></div>
            <span class="arrow-text">Back</span>
        </div>
        <?php echo $this->form()->openTag($form); ?>
        <h1>Registration</h1>
        <p>Create an account if you haven't already</p>
        <div class="d-flex mt-5 position-relative justify-content-lg-center">
            <?php echo $this->formElement($emailRegistration); ?>
            <div class="invalid-tooltip" id="warningMesEmail">
                Incorrect email!
            </div>
        </div>
        <div class="d-flex mt-4 position-relative justify-content-lg-center">
            <?php echo $this->formElement($passwordRegister); ?>
            <div class="invalid-tooltip" id="warningMesPassword">
                Password do not be less 8 letters!
            </div>
        </div>
        <div class="d-flex mt-4 position-relative justify-content-lg-center">
            <?php echo $this->formElement($repeatPassword); ?>
            <div class="invalid-tooltip" id="warningMesRepeatPassword">
                Passwords aren't equal!
            </div>
        </div>
        <?php echo $this->formButton($submitRegister, 'Register'); ?>
        <?php echo $this->form()->closeTag(); ?>
    </main>
</div>
<script src="/js/jquery-3.5.1.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/js/script.js"></script>
<script type="module" src="/js/validation/validationSignIn.js"></script>
<script type="module" src="/js/validation/validation.js"></script>
</body>
</html>
