<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Thank You!</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
  <main class="w-100 position-absolute text-center bottom-50">
      <h1>Thank you!</h1>
      <p>A new generated password has been sent to your email. Please check your email</p>
      <a href="sign" class="btn btn-dark btn-lg w-25 mt-3">Go back</a>
  </main>
</body>
</html>

