<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Settings</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="/css/pageStyle.css" rel="stylesheet">
    <link href="/css/svgStyles.css" rel="stylesheet">
</head>
<body class="bg-light">
<main class="d-flex">
    <div class="d-flex flex-column align-items-stretch flex-shrink-0 min-vh-100">
        <div class="d-flex align-items-center flex-shrink-0 p-2 link-dark text-decoration-none" style="position: absolute;
                                                                                                       top: 0;
                                                                                                       left: 0;
                                                                                                       width: 100%;
                                                                                                       background-color: #f2f0f0;
                                                                                                       opacity: 0.7;
                                                                                                       box-shadow: 0 10px 10px rgba(0, 0, 0, .3);
                                                                                                       ">
            <img class="bi pe-none me-2" id="navPict" src="/img/settings.svg">
            <span class="fs-5 fw-bold me-3">Settings</span>
        </div>
        <div class="scrollarea mt-5">
            <div class="mt-5" style="background-color: #f2f0f0; width: 150%; margin-left: 15%; box-shadow: 0 5px 5px 0px rgba(0, 0, 0, .3);">
                <div class="d-flex border-bottom">
                    <a href="changepassword" class="list-group-item list-group-item-action bg-light border-0 py-3"
                       aria-current="true">
                        <div class="d-flex w-100 align-items-center justify-content-between">
                            <strong class="mb-1">Change password</strong>
                        </div>
                        <div class="col-10 mb-1 small">
                            To change your password, enter your previous password and create a new one.
                        </div>
                    </a>
                </div>
            </div>
        </div>

        <div class="scrollarea mt-1">
                    <div class="mt-5" style="background-color: #f2f0f0; width: 150%; margin-left: 15%; box-shadow: 0 5px 5px 0px rgba(0, 0, 0, .3);">
                        <div class="d-flex border-bottom">
                            <a href="deleteUser"class="list-group-item list-group-item-action bg-light border-0 py-3"
                               aria-current="true">
                                <div class="d-flex w-100 align-items-center justify-content-between">
                                    <strong class="mb-1">Delete Account</strong>
                                </div>
                                <div class="col-10 mb-1 small">
                                    Attention! In case of deletion, you will not be able to restore your account.
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
    </div>
</main>
</body>
</html>



