<!doctype html>
<html lang="en" id="element">
<head>
    <meta charset="utf-8">
    <title>Edit Profile</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="/css/svgStyles.css" rel="stylesheet">
    <link href="/css/pageStyle.css" rel="stylesheet">

    <style>
        #element::-webkit-scrollbar {
		  	width: 10px;
		}

		#element::-webkit-scrollbar-track {
			webkit-box-shadow: 5px 5px 5px -5px rgba(34, 60, 80, 0.2) inset;
		   	background-color: #f9f9fd;
		   	border-radius: 10px;
		}

		#element::-webkit-scrollbar-thumb {
			border-radius: 10px;
			background: linear-gradient(180deg, #00c6fb, #005bea);
		}
    </style>

</head>
<body class="bg-light">
<?php
$emailInput = $form->get('email[]');

$phoneInput = $form->get('phone[]');
if ($phones === null) {
    $phoneInput->setAttribute('value', '');
}
$uploadPhoto = $form->get('file');

$lastNameInput = $form->get('lastNameInput');
$lastNameInput->setAttribute('value', $user["lastname"]);

$firstNameInput = $form->get('firstNameInput');
$firstNameInput->setAttribute('value', $user["firstname"]);

$middleNameInput = $form->get('middleNameInput');
$middleNameInput->setAttribute('value', $user["middlename"]);

$passwordInput = $form->get('passwordInput');
$passwordInput->setAttribute('value', $user["password"]);
$genderDropdown = $form->get("dropdownGender");
$skypeInput     = $form->get('skypeInput');
$skypeInput->setAttribute('value', $user["skype"]);

$checkActive = $form->get('active');
$checkActive->setAttribute('value', $user["is_online"]);

$checkAdmin = $form->get('admin');
$checkAdmin->setAttribute('value', $user["is_admin"]);

$submit = $form->get('submit');
$date   = $form->get("date");
$form->setAttribute('action', $this->url('edit', ['action' => 'edit']));
$form->setAttribute('class', 'needs-validation row mt-5');
$form->setAttribute('novalidate', 'true');
$form->prepare();

echo $this->formHidden($form->get('id'));
?>
<main class="d-flex">
    <div class="d-flex flex-column align-items-stretch flex-shrink-0 min-vh-100">
            <div class="d-flex align-items-center flex-shrink-0 p-2 link-dark text-decoration-none" style="position: absolute;
                                                                                                                   top: 0;
                                                                                                                   left: 0;
                                                                                                                   width: 100%;
                                                                                                                   background-color: #f2f0f0;
                                                                                                                   opacity: 0.7;
                                                                                                                   box-shadow: 0 10px 10px rgba(0, 0, 0, .3);
                                                                                                                   ">
            <img class="bi pe-none me-2" id="navPict" src="/img/pencil.svg">
            <span class="fs-5 fw-bold me-3">Edit Profile</span>
        </div>
        <div class="scrollarea" style="max-width: 100vh;">
            <div class="" style="background-color: #f2f0f0; margin-top: 12%; width: 140%; margin-left: 10%; margin-bottom:5%; border-radius: 6%;">
                <?php echo $this->form()->openTag($form); ?>
                <div class="col text-center">
                    <div class="rounded-5" id="avatarGrid">
                        <img class="m-4 mt-5" id="avatar" name="avatar" src=<?php echo $user["photo"] ?>>
                    </div>
                    <div class="col-auto">
                        <?php echo $this->formFile($uploadPhoto) ?>
                        <label for="file">Upload a photo</label>
                    </div>
                    <div class="row mt-5 justify-content-center">
                        <div class="col-auto">
                            <h4 class=" fw-light">First name:</h4>
                        </div>
                        <div class="col-auto">
                            <div class="ps-5 input-group w-100 align-self-center">
                                <?php echo $this->formElement($firstNameInput) ?>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-5 justify-content-center">
                        <div class="col-auto">
                            <h4 class=" fw-light">Last name:</h4>
                        </div>
                        <div class="col-auto">
                            <div class="ps-5 input-group w-100 align-self-center">
                                <?php echo $this->formElement($lastNameInput) ?>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-5 justify-content-center">
                        <div class="col-auto">
                            <h4 class=" fw-light">Middle name: <br><h6 class="small fw-light mt-0">(if exist)</h6></h4>
                        </div>
                        <div class="col-auto">
                            <div class="ps-3 input-group w-100 align-self-center">
                                <?php echo $this->formElement($middleNameInput) ?>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-5 justify-content-center">
                        <div class="col-auto">
                            <h4 class="fw-light mt-1">Password:</h4>
                        </div>
                        <div class="col-auto">
                            <div class="input-group w-100 align-self-center">
                                <?php echo $this->formElement($passwordInput) ?>
                            </div>
                            <a href="#" class="btn btn-outline-success text-center mt-3 w-auto px-3 ">Generate and send
                                password</a>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="row mt-5">
                        <div class="col-auto">
                            <h4 class="fw-light">Gender:</h4>
                        </div>
                        <div class="col-auto">
                            <?php echo $this->formElement($genderDropdown->setAttribute('value', $user["gender"])) ?>
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col-auto">
                            <h4 class="fw-light">Date of birthday: </h4>
                        </div>
                        <div class="col-auto">
                            <div class="input-group w-100 align-self-center">
                                <?php echo $this->formElement($date->setAttribute('value', $user["dob"])) ?>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col-auto">
                            <h4 class="fw-light mt-2">Email(s):</h4>
                        </div>
                        <div class="col-auto" id="emailArea">
                            <?php foreach ($emails as $email) : ?>
                                <div class="position-relative justify-content-lg-center mt-2 w-100 d-flex align-self-center">
                                    <?php echo $this->formElement($emailInput->setAttribute('value', $email["email"])) ?>
                                    <div class="invalid-tooltip" id="warningMesEmail">
                                        Incorrect email!
                                    </div>
                                    <button type="button" name="closeButton" class="btn-close mt-2 ms-1"
                                            aria-label="Close"></button>
                                </div>
                            <?php endforeach; ?>
                            <a id="addEmail" class="btn btn-outline-success text-center mt-3 w-auto px-3">Add new
                                Email</a>
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col-auto">
                            <h4 class="fw-light mt-2">Phone number(s):</h4>
                        </div>
                        <div class="col-auto" id="phoneArea">
                            <?php foreach ($phones as $phone) : ?>
                                <div class="position-relative mt-2 justify-content-lg-center w-100 d-flex align-self-center">
                                    <?php echo $this->formElement($phoneInput->setAttribute('value', $phone["telephone"])) ?>
                                    <div class="invalid-tooltip" id="warningMesPhone">
                                        Incorrect phone number!!
                                    </div>
                                    <button type="button" name="closeButton" class="btn-close mt-2 ms-1"
                                            aria-label="Close"></button>
                                </div>
                            <?php endforeach; ?>
                            <a id="addPhone" class="btn btn-outline-success text-center mt-3 w-auto px-3">Add new
                                Phone Number</a>
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col-auto">
                            <h4 class="fw-light">Skype:</h4>
                        </div>
                        <div class="col-auto">
                            <div class="input-group w-100 align-self-center">
                                <?php echo $this->formElement($skypeInput) ?>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col-auto">
                            <h4 class="fw-light">Active:</h4>
                        </div>
                        <div class="col-auto">
                            <div class="form-check">
                                <?php echo $this->formElement($checkActive) ?>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col-auto">
                            <h4 class="fw-light">Administrator:</h4>
                        </div>
                        <div class="col-auto">
                            <div class="form-check">
                                <?php echo $this->formElement($checkAdmin) ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="text-center" style="margin-bottom: 2%;">
                    <button id="deleteButton" style="margin-bottom: 0%;" type="button" class="btn btn-danger mt-3 btn-lg mt-5 w-auto px-5 me-3">
                        Delete profile
                    </button>
                    <?php echo $this->formButton($submit, 'Save changes'); ?>
                </div>
                <?php echo $this->form()->closeTag($form); ?>
            </div>
        </div>
    </div>
</main>
<script src="/js/jquery-3.5.1.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script type="module" src="/js/validation/validation.js"></script>
<script type="module" src="/js/validation/validationEditProfile.js"></script>
<script type="module" src="/js/editForAdmin.js"></script>
</body>
</html>

