<!doctype html>
<html lang="en" id="element">
<head>
    <meta charset="utf-8">
    <title>Chats</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="/css/pageStyle.css" rel="stylesheet">
    <link href="/css/svgStyles.css" rel="stylesheet">
    <style>
            #element::-webkit-scrollbar {
                width: 10px;
            }

            #element::-webkit-scrollbar-track {
                webkit-box-shadow: 5px 5px 5px -5px rgba(34, 60, 80, 0.2) inset;
                background-color: #f9f9fd;
                border-radius: 10px;
            }

            #element::-webkit-scrollbar-thumb {
                border-radius: 10px;
                background: linear-gradient(180deg, #00c6fb, #005bea);
            }
    </style>
</head>
<body class="bg-light">
<?php
$search         = $form->get('search');
$submit         = $form->get('submit');
$date           = $form->get('date[]');


$form->setAttribute('action', $this->url('edit', ['action' => 'edit']));
$form->setAttribute('class', 'd-flex align-items-center flex-shrink-0 p-3 link-dark text-decoration-none border-bottom');
$form->prepare();

echo $this->formHidden($form->get('id'));

?>
<main class="d-flex flex-nowrap">
    <div class="d-flex flex-column align-items-stretch flex-shrink-0 min-vh-100">
        <?php echo $this->form()->openTag($form); ?>
        <div class="d-flex align-items-center flex-shrink-0 p-2 link-dark text-decoration-none" style="position: absolute;
                                                                                                       top: 0;
                                                                                                       left: 0;
                                                                                                       width: 100%;
                                                                                                       background-color: #f2f0f0;
                                                                                                       opacity: 0.7;
                                                                                                       box-shadow: 0 10px 10px rgba(0, 0, 0, .3);
                                                                                                               ">
        <img class="bi pe-none me-2" width="30" height="24" src="/img/comments.svg">
        <span class="fs-5 fw-bolder me-3">Chats</span>
        <div class="d-flex w-100 justify-content-end">
            <div class="w-100 d-flex" role="search">
                <?php echo $this->formElement($search) ?>
            </div>
            <div class="ms-2">
                <select class="form-select bg-light w-auto border-0" id="dropdownGender" name="dropdownGender" aria-label="Default select example">
                    <option selected>Gender</option>
                    <option value="1">Female</option>
                    <option value="2">Male</option>
                </select>
            </div>
            <div class="input-group w-auto ms-2 align-self-center">
                <?php echo $this->formElement($date) ?>
            </div>
            <h6 class="text-dark mx-2 mt-2">to</h6>
            <div class="input-group w-auto align-self-center">
                <?php echo $this->formElement($date) ?>
            </div>
            <?php echo $this->formButton($submit, 'Search'); ?>
            </div>
        </div>
        <?php echo $this->form()->closeTag(); ?>
        <div class="list-group list-group-flush border-bottom scrollarea" id="result" style="background-color: white;
                                                                                             width: 220%;
                                                                                             margin-top: 15%;
                                                                                             margin-left: 30%;
                                                                                             ">
            <div id="existDialogs" style="border-radius: 10px;">
                <?php foreach ($dialogsExist as $index => $dialog) : ?>
                <?php if (($latestMessageAndTime[$index]["id_send"] === $userId) ||
                ($latestMessageAndTime[$index]["id_send"] != $userId &&
                    $latestMessageAndTime[$index]["open_at"] !== null)) : ?>
                <a href="<?php echo $this->url('chat', ['action' => 'chat', 'id' => $dialog["staffs.id"]]) ?>"
                   class="list-group-item list-group-item-action py-3 lh-sm">
                    <?php else : ?>
                    <a href="<?php echo $this->url('chat', ['action' => 'chat', 'id' => $dialog["staffs.id"]]) ?>"
                       class="list-group-item list-group-item-action py-3 lh-sm" style="background: #cce5ff">
                        <?php endif; ?>
                        <div class="d-flex">
                            <img class="rounded me-2 dialogPict" src=<?php echo $dialog["photo"] ?>>
                            <div class="d-flex w-100 align-items-center justify-content-between">
                                <strong class="mb-1"><?php echo $dialog["lastname"] . " " . $dialog["firstname"] . " " . $dialog["middlename"] ?></strong>
                                <small class="text-muted"><?php echo date('j M H:i', strtotime($latestMessageAndTime[$index]["send_at"])); ?></small>
                            </div>
                        </div>
                        <div class="col-10 small mt-1">
                            <?php echo $latestMessageAndTime[$index]["id_send"] === $userId ?
                                '<strong> You: </strong>' . $latestMessageAndTime[$index]["letter"] :
                                $latestMessageAndTime[$index]["letter"] ?>
                        </div>
                    </a>
                    <?php endforeach; ?>
            </div>
            <h5 class="text-dark mx-auto mt-3">Users with whom you do not have a dialogue:</h5>
            <div id="notExistDialogs">
                <?php foreach ($dialogsNotExist as $dialog) : ?>
                    <div class="list-group-item py-3 lh-sm">
                        <div class="d-flex">
                            <img class="rounded me-2 dialogPict" src=<?php echo $dialog["photo"] ?>>
                            <div class="d-flex w-100 align-items-center justify-content-between">
                                <strong class="mb-1"><?php echo $dialog["lastname"] . " " . $dialog["firstname"] . " " . $dialog["middlename"] ?></strong>
                            </div>
                            <a href="<?php echo $this->url('chat', ['action' => 'chat', 'id' => $dialog["id"]]) ?>"
                               class="btn btn-primary">Write</a>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="d-flex justify-content-center p-3 mb-3" style="margin-left: 130%;">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                    <li class="page-item active"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item"><a class="page-link" href="#">Next</a></li>
                </ul>
            </nav>
        </div>
    </div>
</main>
<script src="/js/script.js"></script>
<script src="/js/jquery-3.5.1.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script type="module" src="/js/chatsFilter.js"></script>
</body>
</html>
