<!doctype html>
<html lang="en" id="element">
<head>
    <meta charset="utf-8">
    <title>Chats</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="/css/svgStyles.css" rel="stylesheet">
    <link href="/css/pageStyle.css" rel="stylesheet">
    <style>
            #element::-webkit-scrollbar {
                width: 10px;
            }

            #element::-webkit-scrollbar-track {
                webkit-box-shadow: 5px 5px 5px -5px rgba(34, 60, 80, 0.2) inset;
                background-color: #f9f9fd;
                border-radius: 10px;
            }

            #element::-webkit-scrollbar-thumb {
                border-radius: 10px;
                background: linear-gradient(180deg, #00c6fb, #005bea);
            }
    </style>
</head>
<body class="bg-light">
<?php
$messageInput = $form->get('message');
$send         = $form->get('send');

$form->setAttribute('action', $this->url('chat', ['action' => 'chat']));
$form->setAttribute('class', 'position-relative bottom-0 d-flex m-1');
$form->prepare();

echo $this->formHidden($form->get('id'));
?>
<main class="flex-nowrap">
    <div class="d-flex flex-column align-items-stretch flex-shrink-0 min-vh-100" style="width: 180%; margin-left: 20%; margin-top: 5%;">
        <div class="d-flex align-items-center flex-shrink-0 p-3 link-dark bg-light text-decoration-none border-bottom" style="background-color: #f2f0f0; border-radius: 10px;
                                                                                                                              box-shadow: 0 1px 4px rgba(0, 0, 0, 1),
                                                                                                                              -23px 0 20px -23px rgba(0, 0, 0, .8),
                                                                                                                              23px 0 20px -23px rgba(0, 0, 0, .8),
                                                                                                                              0 0 40px rgba(0, 0, 0, .1) inset;">
            <div class="d-flex text-muted pt-1 w-100">
                <img class="rounded me-2 dialogPict" src="<?php echo $senderName["photo"] ?>">
                <p class="mb-0 mt-1">
                    <strong class="d-block text-dark"><?php echo
                              $senderName["lastname"] . " "
                            . $senderName["firstname"] . " "
                            . $senderName["middlename"] ?></strong>
                </p>
                <p class="ms-auto mb-0 me-3">
                    <?php echo $senderName["is_online"] ? '<strong class="d-block text-success fw-light">Online</strong>' :
                        '<strong class="d-block text-danger fw-light">Offline</strong>' ?>
                </p>
            </div>
        </div>
        <div class="scrollbar" style="background-color: #f2f0f0; margin-top: 2%; border-radius: 10px 10px 0 0;">
            <div class="text-center">
                <a id="load" name="1" class="btn btn-primary px-4 py-2 align-content-center mt-3 btn-sm rounded">Load
                    more</a>
            </div>
                <?php foreach ($messages as $message): ?>
                    <?php if ($message["id_get"] === $userId) : ?>
                        <div class="d-flex w-50 rounded-3 mt-4 m-2 p-1 sender">
                            <img class="rounded me-2 dialogPict" src="<?php echo $senderName["photo"] ?>"/>
                            <h6 class="ms-2 fw-bolder my-auto"><?php echo $message["letter"] ?></h6>
                            <span class="ms-auto small"><?php echo date("H:i", strtotime($message["send_at"])) ?></span>
                        </div>
                    <?php else :?>
                        <div class="d-flex ms-auto mt-4 w-50 rounded-3 m-2 p-1 getter">
                            <img class="rounded me-2 dialogPict" src="<?php echo $photo["photo"] ?>"/>
                            <h6 class="ms-2 fw-bolder my-auto"> <?php echo $message["letter"] ?></h6>
                            <span class="ms-auto small"> <?php echo date("H:i", strtotime($message["send_at"])) ?> </span>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
        </div>
            <div style="border-radius: 0 0 10px 10px; background-color: #f2f0f0; margin-bottom: 3%;">
                <?php echo $this->form()->openTag($form); ?>
                <?php echo $this->formElement($messageInput) ?>
                <?php echo $this->formButton($send, 'Send'); ?>
                <?php echo $this->form()->closeTag(); ?>
            </div>
    </div>
</main>
<script src="/js/script.js"></script>
<script src="/js/jquery-3.5.1.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script type="module" src="/js/sendMessage.js"></script>
</body>
</html>
