<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Profile</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="/css/svgStyles.css" rel="stylesheet">
    <link href="/css/pageStyle.css" rel="stylesheet">
</head>
<body class="bg-light">
<main class="d-flex">
    <div class="d-flex flex-column align-items-stretch flex-shrink-0 min-vh-100">
        <div class="d-flex align-items-center flex-shrink-0 p-2 link-dark text-decoration-none" style="position: absolute;
                                                                                                       top: 0;
                                                                                                       left: 0;
                                                                                                       width: 100%;
                                                                                                       background-color: #f2f0f0;
                                                                                                       opacity: 0.7;
                                                                                                       box-shadow: 0 10px 10px rgba(0, 0, 0, .3);
                                                                                                       ">
            <a href="<?php echo $this->url('profile', ['id' => $userId])?>" class="d-flex align-items-center me-md-auto text-decoration-none">
                <span class="fs-4 text-dark">Messanger</span>
            </a>
            <img class="bi pe-none me-2" id="navPict" src="/img/user.svg">
            <span class="fs-5 fw-bold me-3">User Profile</span>
            <a id="signOut" href="<?php echo $this->url('sign') ?>"
               class="btn text-white btn-sm w-auto px-2 ms-auto" style="background-color: #fc0000; border-radius: 10px; padding: 5px;">Log out</a>
        </div>
        <div class="scrollarea mt-5">
            <div class="mt-3" style="background-color: #f2f0f0; width: 120%; margin-left: 10%; border-radius: 6%;">
                <div class="row mt-5" style="">
                    <div class="col text-center">
                        <h3 class="mt-5 m-3 text-secondary fw-light"><?php echo $user["lastname"] . " "
                                . $user["firstname"] . " "
                                . $user["middlename"] ?></h3>
                        <img class="m-4" id="avatar" src=<?php echo $user["photo"] ?>>
                    </div>
                    <div class="col">
                        <div class="row mt-5">
                            <h4 class="fw-light">Gender: <b
                                        class="fw-bold"><?php echo $user["gender"] ? 'Male' : 'Female' ?></b></h4>
                        </div>
                        <div class="row mt-5">
                            <h4 class="fw-light">Date of birthday: <b
                                        class="fw-bold"><?php echo date('d.m.Y', strtotime($user["dob"])); ?></b></h4>
                        </div>
                        <div class="row mt-5">
                            <div class="col-auto">
                                <h4 class="fw-light">Email(s):</h4>
                            </div>
                            <div class="col-auto">
                                <?php foreach ($emails as $email) : ?>
                                    <h4><b><?php echo $email["email"] ?></b></h4>
                                <?php endforeach; ?>
                            </div>
                        </div>
                        <div class="row mt-5">
                            <div class="col-5">
                                <h4 class="fw-light">Phone number(s):</h4>
                            </div>
                            <div class="col-auto">
                            <?php foreach ($phones as $phone) : ?>
                                <h4><b><?php echo $phone["telephone"] ?></b></h4>
                            <?php endforeach; ?>
                            </div>
                        </div>
                        <div class="row mt-5">
                            <div class="col-auto">
                                <h4 class="fw-light">Skype:</h4>
                            </div>
                            <div class="col-1">
                                <h4><b><?php echo $user["skype"] ?></b></h4>
                            </div>
                        </div>
                    </div>
                </div>
                <?php if ($profileId === $userId): ?>
                    <div class="col-auto" style="width: 100%; text-align: center; padding-bottom: 4%;">
                        <a id="btn" href="<?php echo $this->url('edit', ['id' => $userId]) ?>"
                        class="btn btn-success btn-lg mt-2 px-5">Edit profile</a>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</main>
</body>
</html>


