<!DOCTYPE html>
<html lang="ru" id="element">
<head>
    <meta charset="utf-8">
    <title>News</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link
    	  href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
    	  rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">
    <link href="/css/svgStyles.css" rel="stylesheet">
    <link href="/css/pageStyle.css" rel="stylesheet">
    <style>
        #pinBoot {
            min-height: 100vh;
        	margin-left: 30%;
            position: relative;
            max-width: 100%;
            width: 30%;
            margin-top: 7%;
        }

        .white-panel {
            background: white;
            box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.3);
            padding: 10px;
            border-radius: 10px;
            margin-bottom: 10%;
        }
        .white-panel img {
        	margin-top: 10px;
        	margin-bottom: 10px;
        	border-radius: 5px;
        	width: 100%;
            max-width: 100%;
            height: auto;
        }
        .white-panel h3 {
        	text-align: center;
            font-size: 1.2em;
        }
        .white-panel:hover {
            box-shadow: 1px 1px 10px rgba(0, 0, 0, 0.5);
            -webkit-transition: all 0.3s ease-in-out;
            -moz-transition: all 0.3s ease-in-out;
            -o-transition: all 0.3s ease-in-out;
            transition: all 0.3s ease-in-out;
            border-radius: 10px;
        }

        .author a {
        	margin-left: 15px;
        	font-size: 1em;
        	text-decoration: none;
            color: #005bea;
        }

        .news-text {
        	word-wrap: break-word;
        }

        .news-info {
        	margin-bottom: 0;
        	text-align: right;
        }
        .news-info img {
        	margin-top: 8px;
        	width: 16px;
        	height: 16px;
        	fill: currentColor;
        }

        #element::-webkit-scrollbar {
		  	width: 10px;
		}

		#element::-webkit-scrollbar-track {
			webkit-box-shadow: 5px 5px 5px -5px rgba(34, 60, 80, 0.2) inset;
		   	background-color: #f9f9fd;
		   	border-radius: 10px;
		}

		#element::-webkit-scrollbar-thumb {
			border-radius: 10px;
			background: linear-gradient(180deg, #00c6fb, #005bea);
		}
    </style>
</head>

<?php
$uploadPhoto = $form->get('fileNews');
$topic = $form->get("topicInput");
$textInfo = $form->get("infoInput");
?>

<body>
    <div class="d-flex align-items-center flex-shrink-0 p-2 link-dark text-decoration-none" style="position: absolute;
                                                                                                       top: 0;
                                                                                                       left: 0;
                                                                                                       width: 100%;
                                                                                                       background-color: #f2f0f0;
                                                                                                       opacity: 0.7;
                                                                                                       box-shadow: 0 10px 10px rgba(0, 0, 0, .3);
                                                                                                       ">
        <img class="bi pe-none me-2" id="navPict" src="/img/newspaper.svg">
        <span class="fs-5 fw-bold me-3">News</span>

        <!-- Кнопка-триггер модального окна -->
        <button type="button" class="btn btn-info" data-bs-toggle="modal" data-bs-target="#exampleModal" style="border-radius: 10px; margin-left: 40%;">
            Create a new
        </button>
    </div>

	<div class="container">
	        <!-- Модальное окно -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content" style="border-radius: 20px; opacity: 0.9;">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Share the news with others</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
                  </div>
                  <div class="modal-body">
                      <div class="col-auto">
                          <?php echo $this->formFile($uploadPhoto) ?>
                          <label for="fileNews">Upload a photo(If you want)</label>
                      </div>

                      <div class="row mt-5">
                          <div class="col-auto">
                              <h5 class="fw-light">Topic name:</h5>
                          </div>
                          <div class="col-auto">
                              <div class="input-group w-100 align-self-center">
                                  <?php echo $this->formElement($topic) ?>
                              </div>
                          </div>
                      </div>

                      <div class="row mt-5">
                          <div class="col-auto">
                              <h5 class="fw-light">Text:</h5>
                          </div>
                          <div class="col-auto">
                              <div class="input-group w-100 align-self-center" style="margin-left: 31%;">
                                  <?php echo $this->formElement($textInfo) ?>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Publish</button>
                  </div>
                </div>
              </div>
            </div>

	        <section id="pinBoot">
	            <article class="white-panel">
	            	<span class="author">
	            		<a href="#">Автор новости Vass</a>
	            	</span>

	                <img src="img/imageNews.jpg" alt="">

	                <h3>Черепашка ниндзя на берегу таганрогского залива</h3>

	                <p class="news-text">
	                	Lorem ipsum occaecat cupidatat non proident. Lorem ipsum occaecat cupidatat non proident. Lorem ipsum
	                </p>

	                <p class="news-info">
	                	<img src="img/eye.svg">
	                	365 | 2:27 6 июня 2015
	                </p>
	            </article>

	            <article class="white-panel">
	            	<span class="author">
	            		<a href="#">Автор новости Vass</a>
	            	</span>

	                <img src="img/imageNews.jpg" alt="">

	                <h3>Черепашка ниндзя на берегу таганрогского залива</h3>

	                <p class="news-text">Lorem ipsum occaecat cupidatat non proident.</p>

	                <p class="news-info">
	                	<img src="img/eye.svg">
	                	365 | 2:27 6 июня 2015
	                </p>
	            </article>

	        </section>
	</div>
</body>
</html>
						