<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
if (!empty($_SESSION["Laminas\Session\Container"]["userId"])) {
    $userId = $_SESSION["Laminas\Session\Container"]["userId"];
} else {
    $userId = 1000;
}
?>
<?= $this->doctype() ?>
<?php if ($this->url() !== "/sign") :?>
<html lang="en">
<div class="d-flex" style="background: linear-gradient(180deg, #e8ffff, #d4caff);">
    <div id="Sidebar" class="flex-column flex-shrink-0 text-white" style="padding-top: 8%; padding-left: 5%;">
        <ul class="nav mt-3 flex-column" style="background-color: #cfcfcf; border-radius: 15px; padding: 10px;" id="mainNav">
            <li class="nav-item">
                <a href="<?php echo $this->url('profile', ['id' => $userId])?>" class="nav-link active" aria-current="page" id="profile">
                    <img class="bi pe-none me-2 bar-pict" src="/img/user.svg">
                    Profile
                </a>
            </li>

            <li>
                <a href="<?php echo $this->url('news')?>" class="nav-link">
                    <img class="bi pe-none me-2 fw-light bar-pict" src="/img/newspaper.svg" id="news">
                        News
                 </a>
            </li>

            <li class="nav-item">
                <a href="<?php echo $this->url('users')?>" class="nav-link" aria-current="page" id="users">
                    <img class="bi pe-none me-2 bar-pict" src="/img/users.svg">
                    Users
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url('messages')?>" class="nav-link" id="messages">
                    <img class="bi pe-none me-2 bar-pict" src="/img/comments.svg">
                    Chats
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url('settings')?>" class="nav-link" id="settings">
                    <img class="bi pe-none me-2 bar-pict" src="/img/settings.svg">
                    Settings
                </a>
            </li>
            <li>
                <a href="#" class="nav-link">
                    <img class="bi pe-none me-2 fw-light bar-pict" src="/img/info.svg" id="info">
                    Help
                </a>
            </li>
        </ul>
    </div>
    <?php endif; ?>
    <?= $this->content; ?>
</div>

<script src="/js/jquery-3.5.1.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/js/script.js"></script>
<script type="module" src="/js/mainNavSwitch.js"></script>

</html>

